apiVersion: v1
kind: Service
metadata:
  name: telegram-chat-backend
  namespace: telegram-chat
  labels:
    app.kubernetes.io/name: telegram-chat-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: js-chat-telegram-widget
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: telegram-chat-backend
